services:
  backend:
    build: ./API
    container_name: node_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: test
    networks:
      - app-network
    volumes:
      - ./API:/usr/src/app
    command: npm start

  frontend:
    build: ./Front
    container_name: angular_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./Front:/usr/src/app

  db:
    build: ./BD
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./BD/data:/var/lib/mysql
      - ./BD/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
