services:
  api:
    build: ./api
    container_name: node_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: Test
    networks:
      - app-network
    volumes:
      - ./api:/usr/src/app
    command: npm start

  front:
    build: ./Front
    container_name: angular_frontend
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - app-network
    volumes:
      - ./frontend:/usr/src/app

  db:
    build: ./db
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
